Repository MJayConstantino/Dianson-Law-Firm-Legal-Management-System, pull requests merged in 2025-03, with the labels that each got.

#3 Feature/sidebar nav
  package-lock.json
  package.json
  src/app/(dashboard)/calendar/page.tsx
  src/app/(dashboard)/documents/page.tsx
  src/app/(dashboard)/layout.tsx
  src/app/(dashboard)/matters/page.tsx
  src/app/(dashboard)/tasks/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/dashboard/dashboardContent.tsx
  src/components/header/header.tsx
  src/components/mode-toggle.tsx
  src/components/sidebar/appSidebar.tsx
  src/components/sidebar/mobileNavMenu.tsx
  src/components/theme-provider.tsx
  src/components/toast-provider.tsx
  src/components/ui/avatar.tsx
  src/components/ui/dialog.tsx
  src/components/ui/dropdown-menu.tsx
  src/components/ui/input.tsx
  src/components/ui/separator.tsx
  src/components/ui/sheet.tsx
  src/components/ui/sidebar.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/sonner.tsx
  src/components/ui/tooltip.tsx
  src/hooks/use-mobile.ts
Labels: enhancement

#4 fixed server side clients and added signout action
  src/app/(dashboard)/layout.tsx
  src/app/layout.tsx
  src/app/test/login/actions.ts
  src/components/active-link-script.tsx
  src/components/dashboard/dashboardContent.tsx
  src/components/header/header.tsx
  src/components/header/mobileSearchDialog.tsx
  src/components/header/signout.tsx
  src/components/sidebar/appSidebar.tsx
  src/components/sidebar/mobileNavMenu.tsx
  src/utils/supabase/middleware.ts
Labels: enhancement

#6 Feature/sidebar nav
  src/app/(dashboard)/layout.tsx
  src/components/header/avatarDropdownMenu.tsx
  src/components/header/createNewButton.tsx
  src/components/header/desktopSearch.tsx
  src/components/header/header.tsx
  src/components/header/mobileSearch.tsx
  src/components/sidebar/appSidebar.tsx
  src/components/ui/sidebar.tsx
Labels: bug

#7 Testing/auth components
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/action-handlers/users.ts
  src/actions/routing.ts
  src/actions/users.ts
  src/app/(auth)/login/page.tsx
  src/app/auth/callback/route.ts
  src/components/auth/Login.tsx
  src/components/auth/SignUp.tsx
  src/components/header/signout.tsx
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/LoginPage.stories.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/SignOut.stories.tsx
  src/stories/SignUpPage.stories.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
Labels: enhancement

#8 Testing/sidebar and header component
  src/components/header/avatarDropdownMenu.tsx
  src/components/header/createNewButton.tsx
  src/stories/SignUpPage.stories.tsx
  src/stories/header/avatarDropdownMenu.stories.tsx
  src/stories/header/createNewButton.stories.tsx
  src/stories/header/desktopSearch.stories.tsx
  src/stories/header/header.stories.tsx
  src/stories/sidebar/appSidebar.stories.tsx
Labels: enhancement

#9 Testing/auth components
  .vscode/extensions.json
  .vscode/settings.json
  package-lock.json
  package.json
  src/action-handlers/users.ts
  src/app/(auth)/signup/page.tsx
  src/components/auth/Login.tsx
  src/components/auth/SignUp.tsx
  src/stories/SignOut.stories.tsx
  src/stories/SignUpPage.stories.tsx
  src/stories/auth/LoginPage.stories.tsx
  src/stories/auth/SignUpPage.stories.tsx
  supabase/.gitignore
  supabase/config.toml
Labels: enhancement

#10 Feature/matters page
  package-lock.json
  package.json
  src/actions/matters.ts
  src/actions/users.ts
  src/app/(dashboard)/matters/[matterId]/not-found.tsx
  src/app/(dashboard)/matters/[matterId]/page.tsx
  src/app/(dashboard)/matters/page.tsx
  src/components/matters/addMatterDialog.tsx
  src/components/matters/dashboardCards/caseDetailsCard.tsx
  src/components/matters/dashboardCards/courtDetailsCard.tsx
  src/components/matters/dashboardCards/opposingCouncilDetailsCard.tsx
  src/components/matters/editableCard.tsx
  src/components/matters/formSteps/assignmentStep.tsx
  src/components/matters/formSteps/basicInformationStep.tsx
  src/components/matters/formSteps/clientInformationStep.tsx
  src/components/matters/formSteps/courtInformationStep.tsx
  src/components/matters/formSteps/getFormSteps.tsx
  src/components/matters/formSteps/opposingCouncilStep.tsx
  src/components/matters/matterDashboard.tsx
  src/components/matters/matterHeader.tsx
  src/components/matters/matterRow.tsx
  src/components/matters/matterTabs.tsx
  src/components/matters/mattersHeader.tsx
  src/components/matters/mattersList.tsx
  src/components/matters/mattersTable.tsx
  src/components/ui/badge.tsx
  src/components/ui/card.tsx
  src/components/ui/dialog.tsx
  src/components/ui/label.tsx
  src/components/ui/popover.tsx
  src/components/ui/select.tsx
  src/components/ui/table.tsx
  src/components/ui/tabs.tsx
  src/components/ui/textarea.tsx
  src/types/matter.type.ts
  src/types/user.type.ts
  src/utils/getStatusColor.ts
  src/utils/getUserDisplayName.ts
Labels: enhancement

#11 Testing/apiendpointsandedgefunctions
  .vscode/extensions.json
  .vscode/settings.json
  package-lock.json
  package.json
  supabase/.gitignore
  supabase/.temp/cli-latest
  supabase/config.toml
  supabase/functions/hello-world/.npmrc
  supabase/functions/hello-world/deno.json
  supabase/functions/hello-world/deno.lock
  supabase/functions/hello-world/index.ts
  supabase/functions/user-crud-actions/.npmrc
  supabase/functions/user-crud-actions/deno.json
  supabase/functions/user-crud-actions/index.ts
  supabase/functions/user-crud-actions/user_mock.data.ts
  tests/newman/auth.json
Labels: documentation, enhancement

#13 fixed dependencies
  .github/workflows/ci.yml
  package-lock.json
  package.json
Labels: bug

#15 Testing/api integ auth test
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  src/components/auth/Emailfield.tsx
  src/components/auth/Footer.tsx
  src/components/auth/GoogleSigninBtn.tsx
  src/components/auth/Header.tsx
  src/components/auth/Login.tsx
  src/components/auth/NameField.tsx
  src/components/auth/PasswordField.tsx
  src/components/auth/SignInBtn.tsx
  src/components/auth/SignUp.tsx
  src/components/auth/SignupBtn.tsx
  src/components/ui/input-field.tsx
  src/stories/auth/EmailField.stories.tsx
  src/stories/auth/Footer.stories.tsx
  src/stories/auth/GoogleBtn.stories.tsx
  src/stories/auth/Header.stories.tsx
  src/stories/auth/NameField.stories.tsx
  src/stories/auth/PasswordField.stories.tsx
  src/stories/auth/SignUpPage.stories.tsx
Labels: enhancement

#16 nextconfig for linter
  eslint.config.mjs
  next.config.ts
  src/action-handlers/users.ts
  src/app/auth/confirm/route.ts
  src/app/test/advlog/actions.ts
  src/components/auth/Login.tsx
  src/components/auth/SignUp.tsx
  src/components/matters/addMatterDialog.tsx
  src/components/matters/dashboardCards/caseDetailsCard.tsx
Labels: bug

#17 fixed lint issues and deployment configurations
  next.config.ts
  package-lock.json
  package.json
  src/app/(dashboard)/matters/[matterId]/not-found.tsx
  src/app/(dashboard)/matters/[matterId]/page.tsx
  src/app/layout.tsx
  src/app/test/advlog/actions.ts
  src/app/test/oauthlog/actions.ts
  src/components/header/header.tsx
  src/components/matters/dashboardCards/caseDetailsCard.tsx
  src/components/matters/dashboardCards/courtDetailsCard.tsx
  src/components/matters/dashboardCards/opposingCouncilDetailsCard.tsx
  src/components/matters/formSteps/getFormSteps.tsx
  src/components/matters/matterHeader.tsx
  src/components/matters/matterRow.tsx
  src/components/matters/matterTabs.tsx
  src/components/matters/mattersTable.tsx
  src/components/tasks/taskHeader.tsx
  tsconfig.json
Labels: enhancement

#19 Feature/task page
  .vscode/settings.json
  src/actions/routing.ts
  src/actions/tasks.ts
  src/app/(auth)/login/loading.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/loading.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(dashboard)/tasks/loading.tsx
  src/app/(dashboard)/tasks/page.tsx
  src/app/auth/callback/route.ts
  src/app/loggedIn/page.tsx
  src/app/loggedIn/user-info.tsx
  src/app/page.tsx
  src/app/test/userpage/page.tsx
  src/app/test/userpage/user-info.tsx
  src/components/auth/GoogleIcon.tsx
  src/components/auth/GoogleSigninBtn.tsx
  src/components/auth/Login.tsx
  src/components/auth/SignUp.tsx
  src/components/auth/SignupBtn.tsx
  src/components/header/avatarDropdownMenu.tsx
  src/components/homepage/footer.tsx
  src/components/homepage/header.tsx
  src/components/homepage/hero-section.tsx
  src/components/homepage/login-btn.tsx
  src/components/homepage/service-section.tsx
  src/components/tasks/taskCard.tsx
  src/components/tasks/taskForm.tsx
  src/components/tasks/taskHeader.tsx
  src/components/tasks/taskList.tsx
  src/components/tasks/taskProvider.tsx
  src/components/tasks/taskRow.tsx
  src/components/tasks/taskTable.tsx
  src/components/ui/skeleton.tsx
  src/stories/task/taskHeader.stories.tsx
  src/types/task.type.ts
Labels: enhancement

#18 improved ui
  src/app/(auth)/login/loading.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/loading.tsx
  src/app/(auth)/signup/page.tsx
  src/app/auth/callback/route.ts
  src/app/loggedIn/page.tsx
  src/app/loggedIn/user-info.tsx
  src/app/page.tsx
  src/app/test/userpage/page.tsx
  src/app/test/userpage/user-info.tsx
  src/components/auth/Login.tsx
  src/components/auth/SignUp.tsx
  src/components/header/avatarDropdownMenu.tsx
  src/components/header/header.tsx
  src/components/homepage/footer.tsx
  src/components/homepage/header.tsx
  src/components/homepage/hero-section.tsx
  src/components/homepage/login-btn.tsx
  src/components/homepage/service-section.tsx
  src/components/ui/skeleton.tsx
Labels: enhancement
