Repository MJayConstantino/Dianson-Law-Firm-Legal-Management-System, pull requests merged in 2025-05, with the labels that each got.

#65 Fix/DashboardLayout
  src/actions/globalSearch.ts
  src/app/(dashboard)/layout.tsx
  src/components/header/globalSearch/searchResults.tsx
Labels: bug

#66 Fix/globalserach truncate
  src/components/header/globalSearch/searchResults.tsx
Labels: bug

#69 Fix/route protection for loggedinpage
  src/app/loggedIn/page.tsx
Labels: bug

#75 Refactor/auth behavior
  src/actions/users.ts
Labels: enhancement

#78 Fix/matter storybook fix
  src/action-handlers/matters.ts
  src/components/header/createNewButton.tsx
  src/components/matters/addMatterDialog.tsx
  src/components/matters/addMatterForm.tsx
  src/components/matters/dashboardCards/caseDetailsCard.tsx
  src/components/matters/dashboardCards/caseDetailsForm.tsx
  src/components/matters/dashboardCards/courtDetailsCard.tsx
  src/components/matters/dashboardCards/courtDetailsForm.tsx
  src/components/matters/dashboardCards/opposingCouncilDetailsCard.tsx
  src/components/matters/dashboardCards/opposingCouncilDetailsForm.tsx
  src/components/matters/editableCard.tsx
  src/components/matters/matterConfirmDeletionDialog.tsx
  src/components/matters/matterHeader.tsx
  src/components/matters/matterRow.tsx
  src/stories/SignOut.stories.tsx
  src/stories/header/SignOut.stories.tsx
  src/stories/header/avatarDropdownMenu.stories.tsx
  src/stories/header/createNewButton.stories.tsx
  src/stories/header/header.stories.tsx
  src/stories/matters/addMatterDialog.stories.tsx
  src/stories/matters/editableCard.stories.tsx
  src/stories/matters/matterConfirmDeletionDialog.stories.tsx
  src/stories/sidebar/appSidebar.stories.tsx
  src/validation/matter.ts
Labels: enhancement

#87 Fix/matter tabs
  src/components/header/header.tsx
  src/components/matters/matterConfirmDeletionDialog.tsx
  src/components/matters/matterTabs.tsx
  src/components/matters/mattersHeader.tsx
  src/components/sidebar/appSidebar.tsx
  src/components/sidebar/mobileNavMenu.tsx
  src/stories/header/createNewButton.stories.tsx
  src/stories/matters/matterHeader.stories.tsx
  src/stories/sidebar/appSidebar.stories.tsx
Labels: enhancement

#90 Testing/matters e2e
  cypress.config.ts
  cypress/e2e/e2e tests.txt
  cypress/e2e/matters.cy.ts
  src/app/(dashboard)/matters/[matterId]/page.tsx
  src/components/matters/dashboardCards/caseDetailsCard.tsx
  src/components/matters/dashboardCards/caseDetailsCardSkeleton.tsx
  src/components/matters/matterDashboard.tsx
  src/components/matters/matterRow.tsx
Labels: documentation

#93 Chore/read me file
  README.md
Labels: documentation

#94 Feat/create new button mobile functionality
  src/components/header/avatarDropdownMenu.tsx
  src/components/header/createNewButton.tsx
Labels: enhancement

#97 Refactor/ Auth UI/UX and storybook regarding changes
  cypress.config.ts
  cypress/e2e/auth.cy.ts
  src/actions/users.ts
  src/app/(auth)/login/page.tsx
  src/components/auth/Emailfield.tsx
  src/components/auth/Footer.tsx
  src/components/auth/GoogleSigninBtn.tsx
  src/components/auth/Login.tsx
  src/components/auth/NameField.tsx
  src/components/auth/PasswordField.tsx
  src/components/auth/SignInBtn.tsx
  src/components/auth/SignUp.tsx
  src/components/ui/input-field.tsx
  src/components/ui/input.tsx
  src/stories/auth/EmailField.stories.tsx
  src/stories/auth/GoogleBtn.stories.tsx
  src/stories/auth/LoginPage.stories.tsx
  src/stories/auth/NameField.stories.tsx
  src/stories/auth/PasswordField.stories.tsx
  src/stories/auth/SignUpPage.stories.tsx
Labels: enhancement

#104 Fix/lists mobile view
  src/app/(dashboard)/matters/[matterId]/loading.tsx
  src/app/(dashboard)/matters/[matterId]/page.tsx
  src/app/(dashboard)/matters/loading.tsx
  src/app/(dashboard)/matters/page.tsx
  src/components/header/avatarDropdownMenu.tsx
  src/components/matters/dashboardCards/caseDetailsForm.tsx
  src/components/matters/matterTabs.tsx
  src/components/matters/mattersList.tsx
Labels: enhancement

#115 Fix/multiple bug fixes
  src/actions/matters.ts
  src/app/(dashboard)/billings/page.tsx
  src/app/(dashboard)/layout.tsx
  src/app/(dashboard)/matters/[matterId]/loading.tsx
  src/app/(dashboard)/matters/[matterId]/page.tsx
  src/app/(dashboard)/matters/page.tsx
  src/app/(dashboard)/tasks/page.tsx
  src/app/(user)/[userId]/page.tsx
  src/app/layout.tsx
  src/app/loggedIn/page.tsx
  src/components/active-link-script.tsx
  src/components/header/avatarDropdownMenu.tsx
  src/components/header/header.tsx
  src/components/homepage/footer.tsx
  src/components/homepage/header.tsx
  src/components/homepage/serviceCard.tsx
  src/components/homepage/serviceSection.tsx
  src/components/loggedIn/actionButtons.tsx
  src/components/loggedIn/userLoggedIn.tsx
  src/components/loggedIn/userProfile.tsx
  src/components/loggedIn/welcomeHeader.tsx
  src/components/matters/matterTabs.tsx
  src/components/sidebar/appSidebar.tsx
  src/components/ui/active-link-script.tsx
  src/components/ui/mode-toggle.tsx
  src/components/ui/sidebar.tsx
  src/components/ui/theme-provider.tsx
  src/components/ui/toast-provider.tsx
  src/components/ui/tooltip.tsx
  src/stories/globalSearch/desktopSearch.stories.tsx
  src/stories/globalSearch/searchDialog.stories.tsx
  src/stories/header/avatarDropdownMenu.stories.tsx
  src/stories/header/createNewButton.stories.tsx
  src/stories/header/header.stories.tsx
  src/stories/homepage/footer.stories.tsx
  src/stories/homepage/heroSection.stories.tsx
  src/stories/homepage/serviceCard.stories.tsx
  src/stories/homepage/serviceSection.stories.tsx
  src/stories/loggedIn/actionButtons.stories.tsx
  src/stories/loggedIn/userLoggedIn.stories.tsx
  src/stories/loggedIn/userProfile.stories.tsx
  src/stories/loggedIn/welcomeHeader.stories.tsx
  src/stories/matters/addMatterDialog.stories.tsx
  src/stories/matters/matterConfirmDeletionDialog.stories.tsx
  src/stories/matters/matterDashboard.stories.tsx
  src/stories/matters/matterHeader.stories.tsx
  src/stories/matters/matterTable.stories.tsx
  src/stories/matters/mattersList.stories.tsx
  src/utils/cookies.ts
Labels: bug, documentation, enhancement

#125 Fix/matter fixes
  cypress.config.ts
  cypress/e2e/matters.cy.ts
  package-lock.json
  package.json
  src/components/matters/addMatterDialog.tsx
  src/components/matters/addMatterForm.tsx
  src/components/matters/dashboardCards/caseDetailsCard.tsx
  src/components/matters/dashboardCards/caseDetailsForm.tsx
  src/components/matters/dashboardCards/courtDetailsCard.tsx
  src/components/matters/dashboardCards/courtDetailsForm.tsx
  src/components/matters/dashboardCards/opposingCouncilDetailsCard.tsx
  src/components/matters/dashboardCards/opposingCouncilDetailsForm.tsx
  src/components/matters/editableCard.tsx
  src/components/ui/form.tsx
  src/validation/matter.ts
Labels: documentation, enhancement
