Repository MJayConstantino/Dianson-Law-Firm-Legal-Management-System, pull requests merged in 2025-04, with the labels that each got.

#20 Feature/matters page
  src/actions/matters.ts
  src/app/(dashboard)/calendar/page.tsx
  src/app/(dashboard)/documents/page.tsx
  src/app/(dashboard)/matters/[matterId]/page.tsx
  src/app/(dashboard)/matters/page.tsx
  src/app/loggedIn/page.tsx
  src/components/matters/addMatterDialog.tsx
  src/components/matters/dashboardCards/caseDetailsCard.tsx
  src/components/matters/dashboardCards/courtDetailsCard.tsx
  src/components/matters/dashboardCards/opposingCouncilDetailsCard.tsx
  src/components/matters/formSteps/assignmentStep.tsx
  src/components/matters/formSteps/basicInformationStep.tsx
  src/components/matters/formSteps/clientInformationStep.tsx
  src/components/matters/formSteps/courtInformationStep.tsx
  src/components/matters/formSteps/getFormSteps.tsx
  src/components/matters/formSteps/opposingCouncilStep.tsx
  src/components/matters/matterHeader.tsx
  src/components/matters/matterRow.tsx
  src/components/matters/matterTabs.tsx
  src/components/matters/mattersHeader.tsx
  src/components/matters/mattersList.tsx
  src/components/matters/mattersTable.tsx
  src/components/sidebar/appSidebar.tsx
  src/components/sidebar/mobileNavMenu.tsx
  src/components/tasks/taskForm.tsx
  src/types/matter.type.ts
  src/types/task.type.ts
  src/utils/formatDateForDisplay.ts
  src/utils/formatDateForInput.ts
  src/utils/getMattersDisplayName.ts
Labels: enhancement

#21 Feature/logged in
  src/app/loggedIn/page.tsx
  src/components/homepage/hero-section.tsx
Labels: enhancement

#22 Feature/task page
  src/actions/tasks.ts
  src/app/(dashboard)/tasks/page.tsx
  src/components/auth/SignUp.tsx
  src/components/tasks/taskCard.tsx
  src/components/tasks/taskForm.tsx
  src/components/tasks/taskHeader.tsx
  src/components/tasks/taskList.tsx
  src/components/tasks/taskRow.tsx
  src/stories/badge.stories.tsx
  src/stories/task/taskHeader.stories.tsx
Labels: enhancement

#24 Fix/auth input fields
  src/actions/users.ts
  src/app/auth/confirm/route.ts
  src/components/auth/Login.tsx
  src/components/auth/SignInBtn.tsx
  src/components/auth/SignUp.tsx
  src/components/ui/input-field.tsx
Labels: bug

#25 /fix
  src/action-handlers/users.ts
Labels: bug

#27 Testing/api integ auth test
  jest.config.ts
  jest.setup.ts
  next.config.ts
  package-lock.json
  package.json
  src/actions/users.ts
  src/components/auth/Header.tsx
  src/components/header/desktopSearch.tsx
  tests/backend/auth/auth-actions.test.ts
  tests/backend/auth/auth-handler.test.ts
  tests/backend/auth/auth-helper.test.ts
  tests/backend/sample.test.ts
  tests/frontend/auth/auth-dynamic.test.tsx
  tests/frontend/auth/auth-static.test.tsx
  tsconfig.json
  tsconfig.test.json
Labels: enhancement

#28 Feature/task page
  src/app/(dashboard)/tasks/page.tsx
  src/components/tasks/taskCard.tsx
  src/components/tasks/taskForm.tsx
  src/components/tasks/taskHeader.tsx
  src/components/tasks/taskList.tsx
  src/components/tasks/taskRow.tsx
  src/types/task.type.ts
  src/utils/getStatusColor.ts
Labels: enhancement

#29 Feature/user avatar
  next.config.ts
  src/actions/users.ts
  src/app/loggedIn/page.tsx
  src/app/loggedIn/user-info.tsx
  src/components/header/avatarDropdownMenu.tsx
  src/components/homepage/loggedIn/actionButtons.tsx
  src/components/homepage/loggedIn/userLoggedIn.tsx
  src/components/homepage/loggedIn/userProfile.tsx
  src/components/homepage/loggedIn/welcomeHeader.tsx
Labels: enhancement

#35 Feature/globalsearch
  package-lock.json
  package.json
  src/actions/globalSearch.ts
  src/actions/sample.ts
  src/components/header/desktopSearch.tsx
  src/components/header/globalSearch/desktopSearch.tsx
  src/components/header/globalSearch/searchByFilters.tsx
  src/components/header/globalSearch/searchDialog.tsx
  src/components/header/globalSearch/searchInFilters.tsx
  src/components/header/globalSearch/searchResults.tsx
  src/components/header/globalSearch/types.ts
  src/components/header/header.tsx
  src/components/ui/collapsible.tsx
  src/components/ui/scroll-area.tsx
  src/stories/header/desktopSearch.stories.tsx
  src/types/billings.type..ts
  src/types/searchResult.type.ts
  src/types/supabase.ts
  src/types/task.type.ts
Labels: enhancement

#36 Documentation/pg functions
  supabase/pg/auth/DELETE_USERS_AUTH_PUBLIC_NEED.sql
  supabase/pg/auth/SYNC_DATA_AUTH_TO_USERS_PUBLIC.sql
  supabase/pg/rpc/Bill_searh.sql
  supabase/pg/rpc/Matter_search.sql
  supabase/pg/rpc/task_search.sql
Labels: documentation

#38 feature: added test db env and made it so that the tests would run on…
  jest.config.ts
  jest.setup.ts
  package-lock.json
  package.json
  src/components/billings/billingsAddDialog.tsx
  src/components/billings/billingsEditDialog.tsx
  src/components/billings/billingsItem.tsx
  src/components/billings/billingsPage.tsx
  src/components/matters/[matterId]/matterBillingPage.tsx
Labels: enhancement

#39 Feature/task page
  src/actions/tasks.ts
  src/components/tasks/taskCard.tsx
  src/components/tasks/taskDeleteDialog.tsx
  src/components/tasks/taskForm.tsx
  src/components/tasks/taskHeader.tsx
  src/components/tasks/taskList.tsx
  src/components/tasks/taskRow.tsx
Labels: enhancement

#40 should run test db ONLY
  package.json
Labels: bug

#41 Feature/task page
  src/actions/tasks.ts
  src/app/(auth)/login/loading.tsx
  src/app/(auth)/signup/loading.tsx
  src/components/auth/Login.tsx
  src/components/auth/SignUp.tsx
  src/components/homepage/hero-section.tsx
  src/components/matters/[matterId]/matterTaskPage.tsx
  src/components/matters/matterTabs.tsx
  src/components/tasks/taskCard.tsx
  src/components/tasks/taskForm.tsx
  src/components/tasks/taskHeader.tsx
  src/components/tasks/taskList.tsx
  src/components/tasks/taskRow.tsx
  src/types/task.type.ts
Labels: enhancement

#44 Testing/global serach storybook
  src/components/header/globalSearch/searchDialog.tsx
  src/stories/globalSearch/searchByFilters.stories.tsx
  src/stories/globalSearch/searchDialog.stories.tsx
  src/stories/globalSearch/searchInFilters.stories.tsx
  src/stories/globalSearch/searchResults.stories.tsx
  supabase/.temp/cli-latest
  tests/frontend/auth/auth-dynamic.test.tsx
  tests/frontend/auth/auth-static.test.tsx
Labels: enhancement

#47 finalized deno stuff for global search
  package.json
  supabase/config.toml
  supabase/functions/global-search-rpc-actions/.npmrc
  supabase/functions/global-search-rpc-actions/deno.json
  supabase/functions/global-search-rpc-actions/index.ts
Labels: enhancement

#49 Testing/auth unit test
  jest.config.ts
  package.json
  src/action-handlers/users.ts
  src/actions/users.ts
  tests/backend/auth/auth-actions.test.ts
  tests/backend/auth/auth-handler.test.ts
  tests/backend/auth/auth-helper.test.ts
  tests/backend/auth/auth-mock-data.ts
  tests/backend/sample.test.ts
Labels: enhancement

#50 Testing/matters page
  src/action-handlers/matters.ts
  src/app/(dashboard)/billings/page.tsx
  src/components/deleteConfirmationDialog.tsx
  src/components/matters/[matterId]/matterBillingPage.tsx
  src/components/matters/addMatterDialog.tsx
  src/components/matters/dashboardCards/caseDetailsCard.tsx
  src/components/matters/dashboardCards/caseDetailsCardSkeleton.tsx
  src/components/matters/dashboardCards/courtDetailsCard.tsx
  src/components/matters/dashboardCards/opposingCouncilDetailsCard.tsx
  src/components/matters/editableCard.tsx
  src/components/matters/matterConfirmDeletionDialog.tsx
  src/components/matters/matterHeader.tsx
  src/components/matters/matterRow.tsx
  src/components/matters/matterTabs.tsx
  src/components/matters/mattersHeader.tsx
  src/components/matters/mattersList.tsx
  src/components/matters/mattersTable.tsx
  src/stories/matters/addMatterDialog.stories.tsx
  src/stories/matters/editableCard.stories.tsx
  src/stories/matters/matterConfirmDeletionDialog.stories.tsx
  src/stories/matters/matterDashboard.stories.tsx
  src/stories/matters/matterHeader.stories.tsx
  src/stories/matters/matterRow.stories.tsx
  src/stories/matters/matterTable.stories.tsx
  src/stories/matters/mattersHeader.stories.tsx
  src/stories/matters/mattersList.stories.tsx
  src/stories/matters/mockMatters.ts
Labels: enhancement

#53 Chore/refactor matters page
  src/app/(dashboard)/matters/page.tsx
  src/components/header/createNewButton.tsx
  src/components/matters/matterHeader.tsx
  src/components/matters/matterTabs.tsx
  src/components/matters/mattersList.tsx
  src/stories/matters/mattersList.stories.tsx
Labels: enhancement

#54 FIX/env redirect link
  package.json
  src/action-handlers/users.ts
Labels: bug

#56 FIX/ More ENV next stuff
  package.json
  src/action-handlers/users.ts
Labels: bug

#60 Testing/ Cypress Set Up and Auth E2E
  cypress.config.ts
  cypress/e2e/auth.cy.ts
  cypress/e2e/sample.cy.ts
  cypress/fixtures/example.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/support/index.d.ts
  next.config.ts
  package-lock.json
  package.json
  src/components/auth/Emailfield.tsx
  tsconfig.json
Labels: enhancement

#61 Testing/matter actions testing
  src/stories/header/desktopSearch.stories.tsx
  supabase/.temp/cli-latest
  supabase/.temp/gotrue-version
  supabase/.temp/pooler-url
  supabase/.temp/postgres-version
  supabase/.temp/project-ref
  supabase/.temp/rest-version
  supabase/.temp/storage-version
  supabase/config.toml
  supabase/functions/matter-crud-actions/.npmrc
  supabase/functions/matter-crud-actions/deno.json
  supabase/functions/matter-crud-actions/index.ts
Labels: documentation, enhancement
